project_dir: "C:\\Users\\jay.young\\OneDrive - Slalom\\Wiiisdom\\projects\\"

project_name: "cli-batch-testing"

test_name: "open_vis_test"

wiiisdom_dir: "C:\\Users\\jay.young\\OneDrive - Slalom\\Wiiisdom\\"


url_cloud: "https://10ax.online.tableau.com"
version_cloud: "2023.2"
user_cloud: "jay.young@slalom.com"
site_cloud: "jyoungslalom"
token_value_cloud: "token"

client_id_cloud: "client_id"
secret_id_cloud: "secret_id"
secret_value_cloud: "secret_value"


url_server: "https://tableauserver.example.com"
version_server: "2023.1"
user_server: "jay.young@slalom.com"
site_server: ""
token_value_server: "token"

client_id_server: "client_id"
secret_id_server: "secret_id"
secret_value_server: "secret_value"